### ISSUE TITLE
hf legic sim / Legic Simulation does not work properly

### ISSUE THREAD

**Issue by raphCode** [RfidResearchGroup/proxmark3#83]
I have the Proxmark 3 RDV4 and tried simulation of a legic prime card.
I used the steps
* hf legic dump (I used a MIM1024 card and had to increase timeouts in the client, otherwise reads would fail)
* hf legic eload 2 <filename>
* hf legic sim 2
If i recall correctly, at this point LED A is activated and as soon as I get close to the reader LED B and C flash fast, they appear in different intensities. The reader does not react at all.

From older forum posts and issues I saw "timing errors" mentioned, but I thought with  https://github.com/RfidResearchGroup/proxmark3/pull/25 this has been fixed.

Can I somehow help with the debugging/development of this feature? I have experience with programming and electronics as well as some tools like oscilloscope.
I do not know where to start or what to check because I'm not familiar with the project yet. Maybe someone has an idea?

**Comment by iceman1001** [comment]
Output from 
**hw version**
**hw status**
**hw tune**

**Comment by raphCode** [comment]
<details>
  <summary>Click to expand console output</summary>
`pm3 --> hw version

Proxmark3 RFID instrument
          

 [ CLIENT ]          
 client: iceman build for RDV40 with flashmem; smartcard;  
          
 [ ARM ]
 bootrom: iceman/master/a17bf8e-dirty-unclean 2019-01-08 15:12:19
      os: iceman/master/a17bf8e-dirty-unclean 2019-01-08 15:12:23

 [ FPGA ]
 LF image built for 2s30vq100 on 2018/ 9/ 8 at 13:57:51
 HF image built for 2s30vq100 on 2018/ 9/ 3 at 21:40:23          

 [ Hardware ]           
  --= uC: AT91SAM7S512 Rev B          
  --= Embedded Processor: ARM7TDMI          
  --= Nonvolatile Program Memory Size: 512K bytes, Used: 248123 bytes (47%) Free: 276165 bytes (53%)          
  --= Second Nonvolatile Program Memory Size: None          
  --= Internal SRAM Size: 64K bytes          
  --= Architecture Identifier: AT91SAM7Sxx Series          
  --= Nonvolatile Program Memory Type: Embedded Flash Memory          

          
pm3 -->  hw status
#db# Memory          
#db#   BIGBUF_SIZE.............40000          
#db#   Available memory........40000          
#db# Tracing          
#db#   tracing ................1          
#db#   traceLen ...............0          
#db# Currently loaded FPGA image          
#db#   mode.................... HF image built for 2s30vq100 on 2018/ 9/ 3 at 21:40:23          
#db# Flash memory          
#db#   Baudrate................24MHz          
#db#   Init....................OK          
#db#   Memory size.............2 mbits / 256kb          
#db#   Unique ID...............0xd567a882a784b326          
#db# Smart card module (ISO 7816)          
#db#   version.................v2.06          
#db# LF Sampling config          
#db#   [q] divisor.............95 (125 KHz)          
#db#   [b] bps.................8          
#db#   [d] decimation..........1          
#db#   [a] averaging...........Yes          
#db#   [t] trigger threshold...0          
#db# LF T55XX config          
#db#   [a] startgap............29*8 (232)          
#db#   [b] writegap............17*8 (136)          
#db#   [c] write_0.............15*8 (120)          
#db#   [d] write_1.............47*8 (376)          
#db#   [e] readgap.............15*8 (120)          
#db# USB Speed          
#db#   Sending USB packets to client...          
#db#   Time elapsed............1500ms          
#db#   Bytes transferred.......825856          
#db#   USB Transfer Speed PM3 -> Client = 550570 Bytes/s          
#db# Various          
#db#   MF_DBGLEVEL.............1          
#db#   ToSendMax...............-1          
#db#   ToSendBit...............0          
#db#   ToSend BUFFERSIZE.......2308          
#db# Installed StandAlone Mode          
#db#    LF HID26 standalone - aka SamyRun (Samy Kamkar)          
pm3 -->  hw tune
          
[=] measuring antenna characteristics, please wait...
          
....
          
[+] LF antenna: 73,08 V - 125.00 kHz          
[+] LF antenna: 42,49 V - 134.00 kHz          
[+] LF optimal: 74,64 V - 126,32 kHz          
[+] LF antenna is OK  
          
[+] HF antenna: 49,14 V - 13.56 MHz          
[+] HF antenna is OK           
          
[+] Displaying LF tuning graph. Divisor 89 is 134khz, 95 is 125khz.
`
</details>

**Comment by iceman1001** [comment]
Good start,  you have latest firmware from Repo,  and your HF antenna works.
Just standard questions.

You can read the legic card well?   Your eload command seems to be missing the filename....  Is that because you edited your post or did you forgot?

**Comment by raphCode** [comment]
I could read the card with the info and reader commands and get data in the first two blocks, the rest are 00. I think this is a plausible result because there is not much data that needs to be stored on the card.
Again, I had to increase the timeout in `client/cmdhflegic.c:736`, function `legic_read_mem` to not have it abort before the wohle card is read.

I thought I added a filename to the eload in my first post, maybe the edit was not sent properly.
I am pretty sure that I did it correctly in the client since a confirmation appeared that 1024 byte were read from the file.

Is there a possibility to use the info command on the emulator memory to confirm dump and eload work as when directly reading the card?

**Comment by iceman1001** [comment]
hm..  the rdmem ?  **hf legic dump** doesn't use **legic_read_mem**   so that is strange.  or did you mean that you tried to just read out all 1024 bytes with **rdmem** command to look?

You would need to fiddle with the info command in order to look at a dump file / emulator memory

**Comment by uhei** [comment]
I second this.

I've also had to increase the timeout in the legic_read_mem() and CmdLegicDump() functions from 3000 to 7000 to have stable read success with MIM1024 cards.

Also the simulation fails. After eloading the card dump and starting sim when getting closer to the reader LED B and C flash, but the reader doesn't react.

I'm running RDV 4 with latest RfidResearchGroup/proxmark3 repo (firmware/client/bootrom).

How can I help to debug this issue?

**Comment by iceman1001** [comment]
I hear ya,
I added a long waiting for reading memory.  Remember that read mem isn't suppose to read the whole memory,  use dump cmd instead.
Also adapted the output,

How about you guys show me some output from using legic commands?

**Comment by uhei** [comment]
Thanks iceman1001!

Just gave it another try with your commits from today. Dump fails with timeout:
```tyrell2:proxmark3 uh$ client/proxmark3 /dev/cu.usbmodemiceman1 


██████╗ ███╗   ███╗ ████╗     ...iceman fork
██╔══██╗████╗ ████║   ══█║      ...dedicated to RDV40
██████╔╝██╔████╔██║ ████╔╝
██╔═══╝ ██║╚██╔╝██║   ══█║    iceman@icesql.net
██║     ██║ ╚═╝ ██║ ████╔╝  https://github.com/iceman1001/proxmark3
╚═╝     ╚═╝     ╚═╝ ╚═══╝ pre v4.0

Keep iceman fork alive with a donation!           https://paypal.me/iceman1001/
MONERO: 43mNJLpgBVaTvyZmX9ajcohpvVkaRy1kbZPm8tqAb7itZgfuYecgkRF36rXrKFUkwEGeZedPsASRxgv4HPBHvJwyJdyvQuP


[=] UART Setting serial baudrate 115200

Proxmark3 RFID instrument
          

 [ CLIENT ]          
 client: iceman build for RDV40 with flashmem; smartcard;  
          
 [ ARM ]
 bootrom: iceman/master/v1.1.0-616-g13ed4f46 2019-01-19 16:23:29
      os: iceman/master/v1.1.0-616-g13ed4f46 2019-01-19 16:23:31

 [ FPGA ]
 LF image built for 2s30vq100 on 2018/ 9/ 8 at 13:57:51
 HF image built for 2s30vq100 on 2018/ 9/ 3 at 21:40:23          

 [ Hardware ]           
  --= uC: AT91SAM7S512 Rev B          
  --= Embedded Processor: ARM7TDMI          
  --= Nonvolatile Program Memory Size: 512K bytes, Used: 248101 bytes (47%) Free: 276187 bytes (53%)          
  --= Second Nonvolatile Program Memory Size: None          
  --= Internal SRAM Size: 64K bytes          
  --= Architecture Identifier: AT91SAM7Sxx Series          
  --= Nonvolatile Program Memory Type: Embedded Flash Memory
```

Info command works and shows all data of all three segments (output omitted):
```pm3 --> hf legic info
Reading tag memory 1024 b...          
.
          

CDF: System Area          
------------------------------------------------------          
MCD: xx, MSN: xx xx xx, MCC: xx OK     
....
```

---
Dump fails:

```
pm3 --> hf legic dump o ../legic_xxx_20190121
[+] TYPE : MIM1024 card (1002 bytes)          
[+] Reading tag memory 1024 b...          
[!] Command execute time-out          
pm3 --> 
```

---

I've tweaked the timeout:

```
tyrell2:proxmark3 uh$ git diff
diff --git a/client/cmdhflegic.c b/client/cmdhflegic.c
index 0f580da9..63efbdab 100644
--- a/client/cmdhflegic.c
+++ b/client/cmdhflegic.c
@@ -899,7 +899,7 @@ int CmdLegicDump(const char *Cmd){
        clearCommandBuffer();
        SendCommand(&c);
        UsbCommand resp;
-       if (!WaitForResponseTimeout(CMD_ACK, &resp, 3000)) {
+       if (!WaitForResponseTimeout(CMD_ACK, &resp, 7000)) {
                PrintAndLogEx(WARNING, "Command execute time-out");
                return 1;
        }
@@ -1263,4 +1263,4 @@ int CmdHFLegic(const char *Cmd) {
 int CmdHelp(const char *Cmd) {
        CmdsHelp(CommandTable);
        return 0;
-}
\ No newline at end of file
+}
```
and gave it another try:

```
pm3 --> hf legic dump o ../legic_xxx_20190121
[+] TYPE : MIM1024 card (1002 bytes)          
[+] Reading tag memory 1024 b...          
Waiting for a response from the proxmark...          
You can cancel this operation by pressing the pm3 button          
[+] Wrote 1024 bytes to ../legic_xxx_20190121.bin          
pm3 -->
```

I will try the simulation tomorrow.

How can I turn on more verbose/debug logging?

**Comment by iceman1001** [comment]
You turn on the debugging with **hf mf dbg 4**  (or 1,2,3,4)     I know,  not the obvious place.. 

I missed the timeout for the dump command.  I pushed a fix for it.  Try again, please!

**Comment by iceman1001** [comment]
I also changed  the timeouts on

- hf legic write
- hf legic restore
- hf legic wipe

Pull and test :)

**Comment by drandreas** [comment]
Looking at the code
 - LED A indicates that the simulator is on
 - LED B indicates that a frame is reserved
 - LED C indicates that a frame is sent (this implies that, the received frame is valid)
As you mentioned you see B and C so that's a good start.

For your Question about debugging:
 

1.  You should run the Simulation for a couple of seconds. The simulator stores the communication in a trace log.
2. after a couple of seconds you should stop the simulation by pressing the button on the Proxmark3.
3. Now you should be able to print a com log using `trace list legic`

This will tell you at what point the communication fails.

As a side note, the official repos simulator might be more stable, since that code uses a more precise time source. However, the official repo has no trace function.

**Comment by iceman1001** [comment]
Any news @uhei  @raphCode  ?

**Comment by uhei** [comment]
Yes @iceman1001 , there are news.

Dumping the card works now:

```
pm3 --> hf legic dump o ../legic_xxx_20190122
[+] TYPE : MIM1024 card (1002 bytes)          
[+] Reading tag memory 1024 b...          
.
          
[+] Wrote 1024 bytes to ../legic_xxx_20190122.bin          
pm3 --> 
```

Simulating the card still fails. LED B and C are flashing fast:

```
pm3 --> hf legic eload 2 ../legic_xxx_20190122
          
[+] Loaded 1024 bytes from file: ../legic_xxx_20190122.bin  to emulator memory
          
pm3 --> hf legic sim 2
pm3 --> #db# Starting Legic emulator, press button to end          
#db# Stopped          

pm3 --> trace list legic
Recorded Activity (TraceLen = 10513 bytes)          
          
Start = Start of Start Bit, End = End of last modulation. Src = Source of Transfer          
LEGIC - Reader Mode: Timings are in ticks (1us == 1.5ticks)
        Tag Mode: Timings are in sub carrier periods (1/212 kHz == 4.7us)          
          
      Start |        End | Src | Data (! denotes parity error)                                           | CRC | Annotation          
------------+------------+-----+-------------------------------------------------------------------------+-----+--------------------          
          0 |        342 | Rdr |16  2a  20  08                                                           |     |           
       1740 |       2082 | Rdr |16  2a  20  08                                                           |     |           
       5493 |       5617 | Rdr |07  61  00  00                                                           |     | IV 0x61          
       5687 |       5813 | Tag |06  3d  00                                                               |     | MIM1024          
       8083 |       8207 | Rdr |07  31  00  00                                                           |     | IV 0x31          
       8277 |       8403 | Tag |06  3d  00                                                               |     | MIM1024          
      16476 |      16818 | Rdr |16  2a  20  08                                                           |     |           
      18216 |      18558 | Rdr |16  2a  20  08                                                           |     |           
      21932 |      22056 | Rdr |07  0b  00  00                                                           |     | IV 0x0B          
      22126 |      22252 | Tag |06  3d  00                                                               |     | MIM1024          
      22305 |      22415 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
      22473 |      22677 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
      22747 |      22999 | Tag |0c  77  02                                                               |     |           
      23223 |      23427 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
      23497 |      23749 | Tag |0c  0e  04                                                               |     |           
      23973 |      24177 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
      24247 |      24499 | Tag |0c  4c  09                                                               |     |           
      24723 |      24943 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
      25013 |      25265 | Tag |0c  5e  09                                                               |     |           
      25489 |      25701 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
      25771 |      26023 | Tag |0c  80  06                                                               |     |           
      29748 |      29872 | Rdr |07  45  00  00                                                           |     | IV 0x45          
      29942 |      30068 | Tag |06  3d  00                                                               |     | MIM1024          
      30121 |      30231 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
      30289 |      30509 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
      30579 |      30831 | Tag |0c  77  02                                                               |     |           
      31055 |      31267 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
      31337 |      31589 | Tag |0c  0e  04                                                               |     |           
      31813 |      32001 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
      32071 |      32323 | Tag |0c  4c  09                                                               |     |           
      32547 |      32767 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
      32837 |      33089 | Tag |0c  5e  09                                                               |     |           
      33313 |      33493 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
      33563 |      33815 | Tag |0c  80  06                                                               |     |           
      35215 |      35427 | Rdr |0b  b6  03  00                                                           |     | WRITE Byte(475)          
      35973 |      36145 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
      36691 |      36871 | Rdr |0b  a1  00  00                                                           |     | READ Byte(80)          
      37249 |      37461 | Rdr |0b  5d  06  00                                                           |     | READ Byte(814)          
      40859 |      40983 | Rdr |07  31  00  00                                                           |     | IV 0x31          
      41053 |      41179 | Tag |06  3d  00                                                               |     | MIM1024          
      41232 |      41366 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
      41424 |      41612 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
      41682 |      41934 | Tag |0c  77  02                                                               |     |           
      42158 |      42386 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
      42456 |      42708 | Tag |0c  0e  04                                                               |     |           
      42932 |      43136 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
      43206 |      43458 | Tag |0c  4c  09                                                               |     |           
      43682 |      43870 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
      43940 |      44192 | Tag |0c  5e  09                                                               |     |           
      44416 |      44620 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
      44690 |      44942 | Tag |0c  80  06                                                               |     |           
      46384 |      46564 | Rdr |0b  89  00  00                                                           |     | READ Byte(68)          
      47110 |      47338 | Rdr |0b  f7  05  00                                                           |     | READ Byte(763)          
      47884 |      48064 | Rdr |0b  0d  00  00                                                           |     | READ Byte(6)          
      48442 |      48654 | Rdr |0b  2f  03  00                                                           |     | READ Byte(407)          
      52058 |      52182 | Rdr |07  45  00  00                                                           |     | IV 0x45          
      52252 |      52378 | Tag |06  3d  00                                                               |     | MIM1024          
      52431 |      52541 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
      52599 |      52819 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
      52889 |      53141 | Tag |0c  77  02                                                               |     |           
      53365 |      53577 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
      53647 |      53899 | Tag |0c  0e  04                                                               |     |           
      54123 |      54311 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
      54381 |      54633 | Tag |0c  4c  09                                                               |     |           
      54857 |      55077 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
      55147 |      55399 | Tag |0c  5e  09                                                               |     |           
      55623 |      55803 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
      55873 |      56125 | Tag |0c  80  06                                                               |     |           
      57567 |      57763 | Rdr |0b  ec  00  00                                                           |     | WRITE Byte(118)          
      58309 |      58473 | Rdr |0b  00  02  00                                                           |     | WRITE Byte(256)          
      59019 |      59199 | Rdr |0b  29  00  00                                                           |     | READ Byte(20)          
      59577 |      59789 | Rdr |0b  96  07  00                                                           |     | WRITE Byte(971)          
      68374 |      68715 | Rdr |16  2a  20  08                                                           |     |           
      70113 |      70455 | Rdr |16  2a  20  08                                                           |     |           
      73832 |      73964 | Rdr |07  71  00  00                                                           |     | IV 0x71          
      74034 |      74160 | Tag |06  3d  00                                                               |     | MIM1024          
      74213 |      74323 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
      74381 |      74585 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
      74655 |      74907 | Tag |0c  77  02                                                               |     |           
      75131 |      75335 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
      75405 |      75657 | Tag |0c  0e  04                                                               |     |           
      75881 |      76085 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
      76155 |      76407 | Tag |0c  4c  09                                                               |     |           
      76631 |      76835 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
      76905 |      77157 | Tag |0c  5e  09                                                               |     |           
      77381 |      77593 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
      77663 |      77915 | Tag |0c  80  06                                                               |     |           
      81648 |      81788 | Rdr |07  5d  00  00                                                           |     | IV 0x5D          
      81858 |      81984 | Tag |06  3d  00                                                               |     | MIM1024          
      82037 |      82139 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
      82197 |      82425 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
      82495 |      82747 | Tag |0c  77  02                                                               |     |           
      82971 |      83151 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
      83221 |      83473 | Tag |0c  0e  04                                                               |     |           
      83697 |      83877 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
      83947 |      84199 | Tag |0c  4c  09                                                               |     |           
      84423 |      84619 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
      84689 |      84941 | Tag |0c  5e  09                                                               |     |           
      85165 |      85377 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
      85447 |      85699 | Tag |0c  80  06                                                               |     |           
      87141 |      87305 | Rdr |0b  10  00  00                                                           |     | WRITE Byte(8)          
      87851 |      88063 | Rdr |0b  f0  07  00                                                           |     | WRITE Byte(1016)          
      88609 |      88813 | Rdr |0b  ec  01  00                                                           |     | WRITE Byte(246)          
      89191 |      89395 | Rdr |0b  a9  05  00                                                           |     | READ Byte(724)          
      92799 |      92915 | Rdr |07  05  00  00                                                           |     | IV 0x05          
      92985 |      93111 | Tag |06  3d  00                                                               |     | MIM1024          
      93164 |      93282 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
      93340 |      93504 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
      93574 |      93826 | Tag |0c  77  02                                                               |     |           
      94050 |      94238 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
      94308 |      94560 | Tag |0c  0e  04                                                               |     |           
      94784 |      94988 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
      95058 |      95310 | Tag |0c  4c  09                                                               |     |           
      95534 |      95730 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
      95800 |      96052 | Tag |0c  5e  09                                                               |     |           
      96276 |      96488 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
      96558 |      96810 | Tag |0c  80  06                                                               |     |           
      98252 |      98472 | Rdr |0b  f1  07  00                                                           |     | READ Byte(1016)          
      99018 |      99206 | Rdr |0b  1a  04  00                                                           |     | WRITE Byte(525)          
      99752 |      99980 | Rdr |0b  7f  05  00                                                           |     | READ Byte(703)          
     100358 |     100570 | Rdr |0b  72  07  00                                                           |     | WRITE Byte(953)          
     103973 |     104105 | Rdr |07  1d  00  00                                                           |     | IV 0x1D          
     104175 |     104301 | Tag |06  3d  00                                                               |     | MIM1024          
     104354 |     104472 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
     104530 |     104718 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
     104788 |     105040 | Tag |0c  77  02                                                               |     |           
     105264 |     105452 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
     105522 |     105774 | Tag |0c  0e  04                                                               |     |           
     105998 |     106218 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
     106288 |     106540 | Tag |0c  4c  09                                                               |     |           
     106764 |     106968 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
     107038 |     107290 | Tag |0c  5e  09                                                               |     |           
     107514 |     107742 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
     107812 |     108064 | Tag |0c  80  06                                                               |     |           
     109506 |     109694 | Rdr |0b  35  00  00                                                           |     | READ Byte(26)          
     110240 |     110428 | Rdr |0b  d8  00  00                                                           |     | WRITE Byte(108)          
     110974 |     111138 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
     111516 |     111696 | Rdr |0b  38  00  00                                                           |     | WRITE Byte(28)          
...
```

Any hints how I can get the time source of the official repo to this one? Which file should I look at?

**Comment by iceman1001** [comment]
That would be the fpga code...   
Looking at your trace shows that the simulation works for some bytes,  and the reader seems to both want to read / write to your pm3.

Just try the offical repo and see if that works better against the reader,  ie the reader reacts?

**Comment by uhei** [comment]
I gave it a try today with the official repo.

More or less same behavior: LEC C and D flashing, but reader doesn't react (door doesn't open).

```
tyrell2:proxmark3 uh$ client/proxmark3 /dev/cu.usbmodem14201 
Prox/RFID mark3 RFID instrument          
bootrom: iceman/master/v1.1.0-616-g13ed4f46 2019-01-19 16:23:29
os: master/v3.1.0-52-g1511ea2-suspect 2019-01-22 20:45:15
fpga_lf.bit built for 2s30vq100 on 2015/03/06 at 07:38:04
fpga_hf.bit built for 2s30vq100 on 2018/11/28 at 08:33:11
SmartCard Slot: available
          
uC: AT91SAM7S512 Rev B          
Embedded Processor: ARM7TDMI          
Nonvolatile Program Memory Size: 512K bytes. Used: 206126 bytes (39). Free: 318162 bytes (61).          
Second Nonvolatile Program Memory Size: None          
Internal SRAM Size: 64K bytes          
Architecture Identifier: AT91SAM7Sxx Series          
Nonvolatile Program Memory Type: Embedded Flash Memory          

proxmark3> hf legic reader
proxmark3> #db# Reading card ...          
#db# Card (MIM 1024) read, use 'hf legic decode' or          
#db# 'data hexsamples 1024' to view results          

hf legic sim 2
proxmark3> #db# Starting Legic emulator, press button to end          
#db# Stopped          

proxmark3> 
```

I've also tried to enable more debugging (`hf mf dbg 4 `) but not more output has been shown.

**Comment by drandreas** [comment]
There is no output that can be enabled with `dbg 4`, since adding serial output,
would make the code too slow.

The come log looks surprisingly clean. But it puzzles me that the received frame length is always 0x0b (11). 11 bits is correct for read, but writes should be 23 bits. I assume 1 or several bit errors.

Let us look at the timings read of byte 0, 1, 2, 3, 4 look fine, tag to reader frame gabs are constant (224 ticks). But the next gap is significantly longer (1442). My best guess would be that the does not handle that case. You could try to double `RWD_CMD_TIMEOUT` and see how it goes.

**Comment by iceman1001** [comment]
Pull latest, I added @drandreas  suggestion of doubling the timeout.

**Comment by uhei** [comment]
> Pull latest, I added @drandreas suggestion of doubling the timeout.

Some minutes ago I've already modified the code.
Now more bytes are read. However door still doesn't open.

```
tyrell2:proxmark3 uh$ git diff
diff --git a/armsrc/legicrfsim.c b/armsrc/legicrfsim.c
index 1816a29c..7417325a 100644
--- a/armsrc/legicrfsim.c
+++ b/armsrc/legicrfsim.c
@@ -46,7 +46,7 @@ static uint32_t last_frame_end; /* ts of last bit of previews rx or tx frame */
 #define RWD_TIME_PAUSE        4 /* 18.9us */
 #define RWD_TIME_1           21 /* RWD_TIME_PAUSE 18.9us off + 80.2us on = 99.1us */
 #define RWD_TIME_0           13 /* RWD_TIME_PAUSE 18.9us off + 42.4us on = 61.3us */
-#define RWD_CMD_TIMEOUT      40 /* 40 * 99.1us (arbitrary value) */
+#define RWD_CMD_TIMEOUT      80 /* 40 * 99.1us (arbitrary value) */
 #define RWD_MIN_FRAME_LEN     6 /* Shortest frame is 6 bits */
 #define RWD_MAX_FRAME_LEN    23 /* Longest frame is 23 bits */
 

----
pm3 --> hf legic eload 2 ../legic_xxx_20190122
          
[+] Loaded 1024 bytes from file: ../legic_xxx_20190122.bin  to emulator memory
          
pm3 --> 
pm3 --> hf legic sim 2
pm3 --> #db# Starting Legic emulator, press button to end          
#db# Stopped          

pm3 --> trace list legic
Recorded Activity (TraceLen = 19385 bytes)          
          
Start = Start of Start Bit, End = End of last modulation. Src = Source of Transfer          
LEGIC - Reader Mode: Timings are in ticks (1us == 1.5ticks)
        Tag Mode: Timings are in sub carrier periods (1/212 kHz == 4.7us)          
          
      Start |        End | Src | Data (! denotes parity error)                                           | CRC | Annotation          
------------+------------+-----+-------------------------------------------------------------------------+-----+--------------------          
          0 |        140 | Rdr |07  4f  00  00                                                           |     | IV 0x4F          
        210 |        336 | Tag |06  3d  00                                                               |     | MIM1024          
       8418 |       8760 | Rdr |16  2a  20  08                                                           |     |           
      10158 |      10500 | Rdr |16  2a  20  08                                                           |     |           
      13878 |      14002 | Rdr |07  19  00  00                                                           |     | IV 0x19          
      14072 |      14198 | Tag |06  3d  00                                                               |     | MIM1024          
      16468 |      16608 | Rdr |07  4f  00  00                                                           |     | IV 0x4F          
      16678 |      16804 | Tag |06  3d  00                                                               |     | MIM1024          
      24886 |      25228 | Rdr |16  2a  20  08                                                           |     |           
      26626 |      26968 | Rdr |16  2a  20  08                                                           |     |           
      30346 |      30494 | Rdr |07  7d  00  00                                                           |     | IV 0x7D          
      30564 |      30690 | Tag |06  3d  00                                                               |     | MIM1024          
      32959 |      33083 | Rdr |07  23  00  00                                                           |     | IV 0x23          
      33153 |      33279 | Tag |06  3d  00                                                               |     | MIM1024          
      41358 |      41700 | Rdr |16  2a  20  08                                                           |     |           
      43098 |      43440 | Rdr |16  2a  20  08                                                           |     |           
      46819 |      46942 | Rdr |07  51  00  00                                                           |     | IV 0x51          
      47012 |      47138 | Tag |06  3d  00                                                               |     | MIM1024          
      49408 |      49548 | Rdr |07  37  00  00                                                           |     | IV 0x37          
      49618 |      49744 | Tag |06  3d  00                                                               |     | MIM1024          
      57822 |      58164 | Rdr |16  2a  20  08                                                           |     |           
      59562 |      59904 | Rdr |16  2a  20  08                                                           |     |           
      63282 |      63406 | Rdr |07  51  00  00                                                           |     | IV 0x51          
      63476 |      63602 | Tag |06  3d  00                                                               |     | MIM1024          
      63655 |      63773 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
      63831 |      64059 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
      64129 |      64381 | Tag |0c  77  02                                                               |     |           
      64605 |      64833 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
      64903 |      65155 | Tag |0c  0e  04                                                               |     |           
      65379 |      65591 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
      65661 |      65913 | Tag |0c  4c  09                                                               |     |           
      66137 |      66325 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
      66395 |      66647 | Tag |0c  5e  09                                                               |     |           
      66871 |      67051 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
      67121 |      67373 | Tag |0c  80  06                                                               |     |           
      71245 |      71377 | Rdr |07  33  00  00                                                           |     | IV 0x33          
      71447 |      71573 | Tag |06  3d  00                                                               |     | MIM1024          
      71626 |      71720 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
      71778 |      71974 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
      72044 |      72296 | Tag |0c  77  02                                                               |     |           
      72520 |      72732 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
      72802 |      73054 | Tag |0c  0e  04                                                               |     |           
      73278 |      73466 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
      73536 |      73788 | Tag |0c  4c  09                                                               |     |           
      74012 |      74232 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
      74302 |      74554 | Tag |0c  5e  09                                                               |     |           
      74778 |      74990 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
      75060 |      75312 | Tag |0c  80  06                                                               |     |           
      76754 |      76950 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
      77020 |      77272 | Tag |0c  77  02                                                               |     |           
      77496 |      77692 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
      77762 |      78014 | Tag |0c  0e  04                                                               |     |           
      78238 |      78442 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
      78512 |      78764 | Tag |0c  4c  09                                                               |     |           
      78988 |      79216 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
      79286 |      79538 | Tag |0c  5e  09                                                               |     |           
      79762 |      79966 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
      80036 |      80288 | Tag |0c  80  06                                                               |     |           
      80554 |      80742 | Rdr |0b  0d  00  00                                                           |     | READ Byte(6)          
      80812 |      81064 | Tag |0c  ea  01                                                               |     |           
      81288 |      81484 | Rdr |0b  0b  00  00                                                           |     | READ Byte(5)          
      81554 |      81806 | Tag |0c  60  0c                                                               |     |           
      82030 |      82258 | Rdr |0b  0f  00  00                                                           |     | READ Byte(7)          
      82328 |      82580 | Tag |0c  9f  08                                                               |     |           
      82804 |      83000 | Rdr |0b  11  00  00                                                           |     | READ Byte(8)          
      83070 |      83322 | Tag |0c  ff  05                                                               |     |           
      83546 |      83742 | Rdr |0b  19  00  00                                                           |     | READ Byte(12)          
      83812 |      84064 | Tag |0c  11  01                                                               |     |           
      84288 |      84484 | Rdr |0b  1b  00  00                                                           |     | READ Byte(13)          
      84554 |      84806 | Tag |0c  02  06                                                               |     |           
      85954 |      86150 | Rdr |0b  2d  00  00                                                           |     | READ Byte(22)          
      86220 |      86472 | Tag |0c  fe  0b                                                               |     |           
      86696 |      86884 | Rdr |0b  2f  00  00                                                           |     | READ Byte(23)          
      86954 |      87206 | Tag |0c  c0  07                                                               |     |           
      87430 |      87626 | Rdr |0b  31  00  00                                                           |     | READ Byte(24)          
      87696 |      87948 | Tag |0c  88  03                                                               |     |           
      88172 |      88376 | Rdr |0b  33  00  00                                                           |     | READ Byte(25)          
      88446 |      88698 | Tag |0c  c0  0c                                                               |     |           
      88922 |      89134 | Rdr |0b  35  00  00                                                           |     | READ Byte(26)          
      89204 |      89456 | Tag |0c  45  07                                                               |     |           
      89722 |      89910 | Rdr |0b  37  00  00                                                           |     | READ Byte(27)          
      89980 |      90232 | Tag |0c  9c  0e                                                               |     |           
      90456 |      90676 | Rdr |0b  39  00  00                                                           |     | READ Byte(28)          
      90746 |      90998 | Tag |0c  80  05                                                               |     |           
      91222 |      91402 | Rdr |0b  3b  00  00                                                           |     | READ Byte(29)          
      91472 |      91724 | Tag |0c  12  09                                                               |     |           
      91948 |      92128 | Rdr |0b  3d  00  00                                                           |     | READ Byte(30)          
      92198 |      92450 | Tag |0c  90  0e                                                               |     |           
      92716 |      92904 | Rdr |0b  29  01  00                                                           |     | READ Byte(148)          
      92974 |      93226 | Tag |0c  48  0d                                                               |     |           
      93450 |      93638 | Rdr |0b  2b  01  00                                                           |     | READ Byte(149)          
      93708 |      93960 | Tag |0c  c0  08                                                               |     |           
      94184 |      94388 | Rdr |0b  2d  01  00                                                           |     | READ Byte(150)          
      94458 |      94710 | Tag |0c  88  01                                                               |     |           
      94934 |      95146 | Rdr |0b  2f  01  00                                                           |     | READ Byte(151)          
      95216 |      95468 | Tag |0c  e0  0d                                                               |     |           
      95692 |      95904 | Rdr |0b  31  01  00                                                           |     | READ Byte(152)          
      95974 |      96226 | Tag |0c  d6  00                                                               |     |           
      96492 |      96680 | Rdr |0b  33  01  00                                                           |     | READ Byte(153)          
      96750 |      97002 | Tag |0c  b0  0d                                                               |     |           
      97226 |      97422 | Rdr |0b  35  01  00                                                           |     | READ Byte(154)          
      97492 |      97744 | Tag |0c  81  01                                                               |     |           
      97968 |      98164 | Rdr |0b  37  01  00                                                           |     | READ Byte(155)          
      98234 |      98486 | Tag |0c  15  06                                                               |     |           
      98710 |      98890 | Rdr |0b  39  01  00                                                           |     | READ Byte(156)          
      98960 |      99212 | Tag |0c  a0  0f                                                               |     |           
      99436 |      99632 | Rdr |0b  3b  01  00                                                           |     | READ Byte(157)          
      99702 |      99954 | Tag |0c  80  0f                                                               |     |           
     100178 |     100358 | Rdr |0b  3d  01  00                                                           |     | READ Byte(158)          
     100428 |     100680 | Tag |0c  a9  04                                                               |     |           
     100946 |     101134 | Rdr |0b  b9  02  00                                                           |     | READ Byte(348)          
     101204 |     101456 | Tag |0c  cd  08                                                               |     |           
     101680 |     101884 | Rdr |0b  bb  02  00                                                           |     | READ Byte(349)          
     101954 |     102206 | Tag |0c  40  0f                                                               |     |           
     102430 |     102610 | Rdr |0b  bd  02  00                                                           |     | READ Byte(350)          
     102680 |     102932 | Tag |0c  88  0a                                                               |     |           
     103156 |     103360 | Rdr |0b  bf  02  00                                                           |     | READ Byte(351)          
     103430 |     103682 | Tag |0c  e0  06                                                               |     |           
     103906 |     104094 | Rdr |0b  c1  02  00                                                           |     | READ Byte(352)          
     104164 |     104416 | Tag |0c  39  02                                                               |     |           
     104682 |     104894 | Rdr |0b  c3  02  00                                                           |     | READ Byte(353)          
     104964 |     105216 | Tag |0c  ac  02                                                               |     |           
     105440 |     105636 | Rdr |0b  c5  02  00                                                           |     | READ Byte(354)          
     105706 |     105958 | Tag |0c  e3  07                                                               |     |           
     106182 |     106362 | Rdr |0b  c7  02  00                                                           |     | READ Byte(355)          
     106432 |     106684 | Tag |0c  80  08                                                               |     |           
     106908 |     107120 | Rdr |0b  c9  02  00                                                           |     | READ Byte(356)          
     107190 |     107442 | Tag |0c  80  01                                                               |     |           
     107666 |     107862 | Rdr |0b  cb  02  00                                                           |     | READ Byte(357)          
     107932 |     108184 | Tag |0c  a4  04                                                               |     |           
     108408 |     108620 | Rdr |0b  cd  02  00                                                           |     | READ Byte(358)          
     108690 |     108942 | Tag |0c  03  02                                                               |     |           
     112400 |     112531 | Rdr |07  71  00  00                                                           |     | IV 0x71          
     112601 |     112727 | Tag |06  3d  00                                                               |     | MIM1024          
     112780 |     112890 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
     112948 |     113152 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
     113222 |     113474 | Tag |0c  77  02                                                               |     |           
     113698 |     113902 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
     113972 |     114224 | Tag |0c  0e  04                                                               |     |           
     114448 |     114652 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
     114722 |     114974 | Tag |0c  4c  09                                                               |     |           
     115198 |     115402 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
     115472 |     115724 | Tag |0c  5e  09                                                               |     |           
     115948 |     116160 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
     116230 |     116482 | Tag |0c  80  06                                                               |     |           
     117924 |     118096 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
     118166 |     118418 | Tag |0c  77  02                                                               |     |           
     118642 |     118862 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
     118932 |     119184 | Tag |0c  0e  04                                                               |     |           
     119408 |     119636 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
     119706 |     119958 | Tag |0c  4c  09                                                               |     |           
     120182 |     120362 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
     120432 |     120684 | Tag |0c  5e  09                                                               |     |           
     120908 |     121088 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
     121158 |     121410 | Tag |0c  80  06                                                               |     |           
     121676 |     121864 | Rdr |0b  0d  00  00                                                           |     | READ Byte(6)          
     121934 |     122186 | Tag |0c  ea  01                                                               |     |           
     122410 |     122590 | Rdr |0b  0b  00  00                                                           |     | READ Byte(5)          
     122660 |     122912 | Tag |0c  60  0c                                                               |     |           
     123136 |     123332 | Rdr |0b  0f  00  00                                                           |     | READ Byte(7)          
     123402 |     123654 | Tag |0c  9f  08                                                               |     |           
     123878 |     124074 | Rdr |0b  11  00  00                                                           |     | READ Byte(8)          
     124144 |     124396 | Tag |0c  ff  05                                                               |     |           
     124620 |     124808 | Rdr |0b  19  00  00                                                           |     | READ Byte(12)          
     124878 |     125130 | Tag |0c  11  01                                                               |     |           
     125354 |     125550 | Rdr |0b  1b  00  00                                                           |     | READ Byte(13)          
     125620 |     125872 | Tag |0c  02  06                                                               |     |           
     126978 |     127190 | Rdr |0b  2d  00  00                                                           |     | READ Byte(22)          
     127260 |     127512 | Tag |0c  fe  0b                                                               |     |           
     127736 |     127940 | Rdr |0b  2f  00  00                                                           |     | READ Byte(23)          
     128010 |     128262 | Tag |0c  c0  07                                                               |     |           
     128486 |     128674 | Rdr |0b  31  00  00                                                           |     | READ Byte(24)          
     128744 |     128996 | Tag |0c  88  03                                                               |     |           
     129220 |     129424 | Rdr |0b  33  00  00                                                           |     | READ Byte(25)          
     129494 |     129746 | Tag |0c  c0  0c                                                               |     |           
     129970 |     130166 | Rdr |0b  35  00  00                                                           |     | READ Byte(26)          
     130236 |     130488 | Tag |0c  45  07                                                               |     |           
     130754 |     130918 | Rdr |0b  37  00  00                                                           |     | READ Byte(27)          
     130988 |     131240 | Tag |0c  9c  0e                                                               |     |           
     131464 |     131652 | Rdr |0b  39  00  00                                                           |     | READ Byte(28)          
     131722 |     131974 | Tag |0c  80  05                                                               |     |           
     132198 |     132386 | Rdr |0b  3b  00  00                                                           |     | READ Byte(29)          
     132456 |     132708 | Tag |0c  12  09                                                               |     |           
     132932 |     133120 | Rdr |0b  3d  00  00                                                           |     | READ Byte(30)          
     133190 |     133442 | Tag |0c  90  0e                                                               |     |           
     133709 |     133913 | Rdr |0b  3f  00  00                                                           |     | READ Byte(31)          
     133983 |     134235 | Tag |0c  87  0c                                                               |     |           
     134459 |     134647 | Rdr |0b  41  00  00                                                           |     | READ Byte(32)          
     134717 |     134969 | Tag |0c  c7  04                                                               |     |           
     135193 |     135405 | Rdr |0b  43  00  00                                                           |     | READ Byte(33)          
     135475 |     135727 | Tag |0c  a7  02                                                               |     |           
     135951 |     136155 | Rdr |0b  45  00  00                                                           |     | READ Byte(34)          
     136225 |     136477 | Tag |0c  61  06                                                               |     |           
     136701 |     136905 | Rdr |0b  47  00  00                                                           |     | READ Byte(35)          
     136975 |     137227 | Tag |0c  49  0c                                                               |     |           
     137451 |     137647 | Rdr |0b  49  00  00                                                           |     | READ Byte(36)          
     137717 |     137969 | Tag |0c  80  02                                                               |     |           
     138193 |     138389 | Rdr |0b  4b  00  00                                                           |     | READ Byte(37)          
     138459 |     138711 | Tag |0c  80  01                                                               |     |           
     138935 |     139139 | Rdr |0b  4d  00  00                                                           |     | READ Byte(38)          
     139209 |     139461 | Tag |0c  80  04                                                               |     |           
     141533 |     141729 | Rdr |0b  95  01  00                                                           |     | READ Byte(202)          
     142275 |     142463 | Rdr |0b  89  04  00                                                           |     | READ Byte(580)          
     143009 |     143213 | Rdr |0b  c2  07  00                                                           |     | WRITE Byte(993)          
     143591 |     143779 | Rdr |0b  98  01  00                                                           |     | WRITE Byte(204)          
     147178 |     147318 | Rdr |07  4f  00  00                                                           |     | IV 0x4F          
     147388 |     147514 | Tag |06  3d  00                                                               |     | MIM1024          
     147567 |     147669 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
     147727 |     147923 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
     147993 |     148245 | Tag |0c  77  02                                                               |     |           
     148469 |     148681 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
     148751 |     149003 | Tag |0c  0e  04                                                               |     |           
     149227 |     149439 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
     149509 |     149761 | Tag |0c  4c  09                                                               |     |           
     149985 |     150197 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
     150267 |     150519 | Tag |0c  5e  09                                                               |     |           
     150743 |     150955 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
     151025 |     151277 | Tag |0c  80  06                                                               |     |           
     152677 |     152889 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
     152959 |     153211 | Tag |0c  77  02                                                               |     |           
     153435 |     153631 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
     153701 |     153953 | Tag |0c  0e  04                                                               |     |           
     154177 |     154405 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
     154475 |     154727 | Tag |0c  4c  09                                                               |     |           
     154951 |     155131 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
     155201 |     155453 | Tag |0c  5e  09                                                               |     |           
     155677 |     155889 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
     155959 |     156211 | Tag |0c  80  06                                                               |     |           
     156477 |     156673 | Rdr |0b  0d  00  00                                                           |     | READ Byte(6)          
     156743 |     156995 | Tag |0c  ea  01                                                               |     |           
     157219 |     157407 | Rdr |0b  0b  00  00                                                           |     | READ Byte(5)          
     157477 |     157729 | Tag |0c  60  0c                                                               |     |           
     157953 |     158141 | Rdr |0b  0f  00  00                                                           |     | READ Byte(7)          
     158211 |     158463 | Tag |0c  9f  08                                                               |     |           
     158687 |     158867 | Rdr |0b  11  00  00                                                           |     | READ Byte(8)          
     158937 |     159189 | Tag |0c  ff  05                                                               |     |           
     159413 |     159617 | Rdr |0b  19  00  00                                                           |     | READ Byte(12)          
     159687 |     159939 | Tag |0c  11  01                                                               |     |           
     160163 |     160375 | Rdr |0b  1b  00  00                                                           |     | READ Byte(13)          
     160445 |     160697 | Tag |0c  02  06                                                               |     |           
     161719 |     161923 | Rdr |0b  2d  00  00                                                           |     | READ Byte(22)          
     161993 |     162245 | Tag |0c  fe  0b                                                               |     |           
     162469 |     162673 | Rdr |0b  2f  00  00                                                           |     | READ Byte(23)          
     162743 |     162995 | Tag |0c  c0  07                                                               |     |           
     163219 |     163407 | Rdr |0b  31  00  00                                                           |     | READ Byte(24)          
     163477 |     163729 | Tag |0c  88  03                                                               |     |           
     163953 |     164157 | Rdr |0b  33  00  00                                                           |     | READ Byte(25)          
     164227 |     164479 | Tag |0c  c0  0c                                                               |     |           
     164703 |     164915 | Rdr |0b  35  00  00                                                           |     | READ Byte(26)          
     164985 |     165237 | Tag |0c  45  07                                                               |     |           
     165503 |     165691 | Rdr |0b  37  00  00                                                           |     | READ Byte(27)          
     165761 |     166013 | Tag |0c  9c  0e                                                               |     |           
     166237 |     166433 | Rdr |0b  39  00  00                                                           |     | READ Byte(28)          
     166503 |     166755 | Tag |0c  80  05                                                               |     |           
     166979 |     167183 | Rdr |0b  3b  00  00                                                           |     | READ Byte(29)          
     167253 |     167505 | Tag |0c  12  09                                                               |     |           
     167729 |     167909 | Rdr |0b  3d  00  00                                                           |     | READ Byte(30)          
     167979 |     168231 | Tag |0c  90  0e                                                               |     |           
     168497 |     168685 | Rdr |0b  3f  00  00                                                           |     | READ Byte(31)          
     168755 |     169007 | Tag |0c  87  0c                                                               |     |           
     169231 |     169435 | Rdr |0b  41  00  00                                                           |     | READ Byte(32)          
     169505 |     169757 | Tag |0c  c7  04                                                               |     |           
     169981 |     170193 | Rdr |0b  43  00  00                                                           |     | READ Byte(33)          
     170263 |     170515 | Tag |0c  a7  02                                                               |     |           
     170739 |     170951 | Rdr |0b  45  00  00                                                           |     | READ Byte(34)          
     171021 |     171273 | Tag |0c  61  06                                                               |     |           
     171497 |     171685 | Rdr |0b  47  00  00                                                           |     | READ Byte(35)          
     171755 |     172007 | Tag |0c  49  0c                                                               |     |           
     172231 |     172427 | Rdr |0b  49  00  00                                                           |     | READ Byte(36)          
     172497 |     172749 | Tag |0c  80  02                                                               |     |           
     172973 |     173161 | Rdr |0b  4b  00  00                                                           |     | READ Byte(37)          
     173231 |     173483 | Tag |0c  80  01                                                               |     |           
     173707 |     173895 | Rdr |0b  4d  00  00                                                           |     | READ Byte(38)          
     173965 |     174217 | Tag |0c  80  04                                                               |     |           
     176289 |     176485 | Rdr |0b  79  00  00                                                           |     | READ Byte(60)          
     177031 |     177211 | Rdr |0b  2c  00  00                                                           |     | WRITE Byte(22)          
     177757 |     177953 | Rdr |0b  3c  01  00                                                           |     | WRITE Byte(158)          
     178331 |     178535 | Rdr |0b  17  03  00                                                           |     | READ Byte(395)          
     187107 |     187449 | Rdr |16  2a  20  08                                                           |     |           
     188847 |     189189 | Rdr |16  2a  20  08                                                           |     |           
     192563 |     192695 | Rdr |07  17  00  00                                                           |     | IV 0x17          
     192765 |     192891 | Tag |06  3d  00                                                               |     | MIM1024          
     192944 |     193062 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
     193120 |     193324 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
     193394 |     193646 | Tag |0c  77  02                                                               |     |           
     193870 |     194050 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
     194120 |     194372 | Tag |0c  0e  04                                                               |     |           
     194596 |     194808 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
     194878 |     195130 | Tag |0c  4c  09                                                               |     |           
     195354 |     195550 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
     195620 |     195872 | Tag |0c  5e  09                                                               |     |           
     196096 |     196300 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
     196370 |     196622 | Tag |0c  80  06                                                               |     |           
     200347 |     200479 | Rdr |07  63  00  00                                                           |     | IV 0x63          
     200549 |     200675 | Tag |06  3d  00                                                               |     | MIM1024          
     200728 |     200846 | Rdr |06  39  00  00                                                           |     | ACK 256/1024          
     200904 |     201076 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
     201146 |     201398 | Tag |0c  77  02                                                               |     |           
     201622 |     201810 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
     201880 |     202132 | Tag |0c  0e  04                                                               |     |           
     202356 |     202560 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
     202630 |     202882 | Tag |0c  4c  09                                                               |     |           
     203106 |     203278 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
     203348 |     203600 | Tag |0c  5e  09                                                               |     |           
     203824 |     204044 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
     204114 |     204366 | Tag |0c  80  06                                                               |     |           
     205766 |     205954 | Rdr |0b  01  00  00                                                           |     | READ Byte(0)          
     206024 |     206276 | Tag |0c  77  02                                                               |     |           
     206500 |     206696 | Rdr |0b  03  00  00                                                           |     | READ Byte(1)          
     206766 |     207018 | Tag |0c  0e  04                                                               |     |           
     207242 |     207446 | Rdr |0b  05  00  00                                                           |     | READ Byte(2)          
     207516 |     207768 | Tag |0c  4c  09                                                               |     |           
     207992 |     208204 | Rdr |0b  07  00  00                                                           |     | READ Byte(3)          
     208274 |     208526 | Tag |0c  5e  09                                                               |     |           
     208750 |     208938 | Rdr |0b  09  00  00                                                           |     | READ Byte(4)          
     209008 |     209260 | Tag |0c  80  06                                                               |     |           
     209526 |     209714 | Rdr |0b  0d  00  00                                                           |     | READ Byte(6)          
     209784 |     210036 | Tag |0c  ea  01                                                               |     |           
     210260 |     210472 | Rdr |0b  0b  00  00                                                           |     | READ Byte(5)          
     210542 |     210794 | Tag |0c  60  0c                                                               |     |           
     211018 |     211222 | Rdr |0b  0f  00  00                                                           |     | READ Byte(7)          
     211292 |     211544 | Tag |0c  9f  08                                                               |     |           
     211768 |     211980 | Rdr |0b  11  00  00                                                           |     | READ Byte(8)          
     212050 |     212302 | Tag |0c  ff  05                                                               |     |           
     212526 |     212706 | Rdr |0b  19  00  00                                                           |     | READ Byte(12)          
     212776 |     213028 | Tag |0c  11  01                                                               |     |           
     213252 |     213448 | Rdr |0b  1b  00  00                                                           |     | READ Byte(13)          
     213518 |     213770 | Tag |0c  02  06                                                               |     |           
     214918 |     215146 | Rdr |0b  2d  00  00                                                           |     | READ Byte(22)          
     215216 |     215468 | Tag |0c  fe  0b                                                               |     |           
     215692 |     215872 | Rdr |0b  2f  00  00                                                           |     | READ Byte(23)          
     215942 |     216194 | Tag |0c  c0  07                                                               |     |           
     216418 |     216614 | Rdr |0b  31  00  00                                                           |     | READ Byte(24)          
     216684 |     216936 | Tag |0c  88  03                                                               |     |           
     217160 |     217356 | Rdr |0b  33  00  00                                                           |     | READ Byte(25)          
     217426 |     217678 | Tag |0c  c0  0c                                                               |     |           
     217902 |     218082 | Rdr |0b  35  00  00                                                           |     | READ Byte(26)          
     218152 |     218404 | Tag |0c  45  07                                                               |     |           
     218670 |     218882 | Rdr |0b  37  00  00                                                           |     | READ Byte(27)          
     218952 |     219204 | Tag |0c  9c  0e                                                               |     |           
     219428 |     219656 | Rdr |0b  39  00  00                                                           |     | READ Byte(28)          
     219726 |     219978 | Tag |0c  80  05                                                               |     |           
     220202 |     220422 | Rdr |0b  3b  00  00                                                           |     | READ Byte(29)          
     220492 |     220744 | Tag |0c  12  09                                                               |     |           
     220968 |     221148 | Rdr |0b  3d  00  00                                                           |     | READ Byte(30)          
     221218 |     221470 | Tag |0c  90  0e                                                               |     |           
     221736 |     221932 | Rdr |0b  29  01  00                                                           |     | READ Byte(148)          
     222002 |     222254 | Tag |0c  48  0d                                                               |     |           
     222478 |     222666 | Rdr |0b  2b  01  00                                                           |     | READ Byte(149)          
     222736 |     222988 | Tag |0c  c0  08                                                               |     |           
     223212 |     223424 | Rdr |0b  2d  01  00                                                           |     | READ Byte(150)          
     223494 |     223746 | Tag |0c  88  01                                                               |     |           
     223970 |     224158 | Rdr |0b  2f  01  00                                                           |     | READ Byte(151)          
     224228 |     224480 | Tag |0c  e0  0d                                                               |     |           
     224704 |     224884 | Rdr |0b  31  01  00                                                           |     | READ Byte(152)          
     224954 |     225206 | Tag |0c  d6  00                                                               |     |           
     225472 |     225676 | Rdr |0b  33  01  00                                                           |     | READ Byte(153)          
     225746 |     225998 | Tag |0c  b0  0d                                                               |     |           
     226222 |     226410 | Rdr |0b  35  01  00                                                           |     | READ Byte(154)          
     226480 |     226732 | Tag |0c  81  01                                                               |     |           
     226956 |     227144 | Rdr |0b  37  01  00                                                           |     | READ Byte(155)          
     227214 |     227466 | Tag |0c  15  06                                                               |     |           
     227690 |     227894 | Rdr |0b  39  01  00                                                           |     | READ Byte(156)          
     227964 |     228216 | Tag |0c  a0  0f                                                               |     |           
     228440 |     228636 | Rdr |0b  3b  01  00                                                           |     | READ Byte(157)          
     228706 |     228958 | Tag |0c  80  0f                                                               |     |           
     229182 |     229386 | Rdr |0b  3d  01  00                                                           |     | READ Byte(158)          
     229456 |     229708 | Tag |0c  a9  04                                                               |     |           
     229974 |     230186 | Rdr |0b  b9  02  00                                                           |     | READ Byte(348)          
     230256 |     230508 | Tag |0c  cd  08                                                               |     |           
     230732 |     230936 | Rdr |0b  bb  02  00                                                           |     | READ Byte(349)          
     231006 |     231258 | Tag |0c  40  0f                                                               |     |           
     231482 |     231686 | Rdr |0b  bd  02  00                                                           |     | READ Byte(350)          
     231756 |     232008 | Tag |0c  88  0a                                                               |     |           
     232232 |     232420 | Rdr |0b  bf  02  00                                                           |     | READ Byte(351)          
     232490 |     232742 | Tag |0c  e0  06                                                               |     |           
     232966 |     233178 | Rdr |0b  c1  02  00                                                           |     | READ Byte(352)          
     233248 |     233500 | Tag |0c  39  02                                                               |     |           
     233766 |     233962 | Rdr |0b  c3  02  00                                                           |     | READ Byte(353)          
     234032 |     234284 | Tag |0c  ac  02                                                               |     |           
     234508 |     234712 | Rdr |0b  c5  02  00                                                           |     | READ Byte(354)          
     234782 |     235034 | Tag |0c  e3  07                                                               |     |           
     235258 |     235454 | Rdr |0b  c7  02  00                                                           |     | READ Byte(355)          
     235524 |     235776 | Tag |0c  80  08                                                               |     |           
     236000 |     236204 | Rdr |0b  c9  02  00                                                           |     | READ Byte(356)          
     236274 |     236526 | Tag |0c  80  01                                                               |     |           
     236750 |     236986 | Rdr |0b  cb  02  00                                                           |     | READ Byte(357)          
     237056 |     237308 | Tag |0c  a4  04                                                               |     |           
     237532 |     237728 | Rdr |0b  cd  02  00                                                           |     | READ Byte(358)          
     237798 |     238050 | Tag |0c  03  02                                                               |     |           
```
So, we're making progress! Thanks so far @iceman1001 and @drandreas

**Comment by iceman1001** [comment]
good,  for the sake of saving the time it takes to scroll those paste,   please consider using pastebin.com for it.

I see less and less writes but more and more reads.   Try increasing the timeout evermore  120?

**Comment by uhei** [comment]
> I see less and less writes but more and more reads. Try increasing the timeout evermore 120?

Yeah. That's it. Changed timeout to 120 and now it works!
Thanks a lot @iceman1001 and @drandreas!

**Comment by iceman1001** [comment]
I am closing this one even if  @raphCode  has not confirmed.

**Comment by raphCode** [comment]
I was busy the last days and also had no possibility to test, but I will try with the updated code and report back here. 
The recent changes look very promising, thanks to all who contributed to this issue!

**Comment by raphCode** [comment]
Yep, it works for me too, now!
Again thanks @iceman1001 and @drandreas :)

Maybe a good idea to merge the changes also into the official repo or at least the "normal"/non-rdv4 iceman fork?

**Comment by iceman1001** [comment]
merged to iceman already.
will do offical later,  feel free to do it.
